using MemoryGame.Audio.Events;
using MemoryGame.UI.Events;
using UnityEngine;
using UnityEngine.UI;

namespace MemoryGame.Views
{
    /// <summary>
    /// View component for the Home screen of the Memory Game.
    /// Handles binding UI button clicks to game events and updating audio icons.
    /// </summary>
    public class HomeView : MonoBehaviour
    {
        /// <summary>
        /// Button to start the game from the home screen
        /// </summary>
        [Header("Buttons")]
        public Button startButton;
        
        /// <summary>
        /// Button to reset player progress
        /// </summary>
        public Button resetProgressButton;
        
        /// <summary>
        /// Button to show the level selection screen
        /// </summary>
        public Button levelSelectButton;
        
        /// <summary>
        /// Button to toggle sound effects on/off
        /// </summary>
        public Button sfxButton;
        
        /// <summary>
        /// Button to exit the application
        /// </summary>
        public Button exitButton;
        
        /// <summary>
        /// Button to toggle music on/off
        /// </summary>
        public Button musicButton;
        
        /// <summary>
        /// Image to display the sound effects status (on/off)
        /// </summary>
        [Header("Icons")]
        public Image sfxIcon;
        
        /// <summary>
        /// Image to display the music status (on/off)
        /// </summary>
        public Image musicIcon;
        
        /// <summary>
        /// Sprite to show when sound effects are enabled
        /// </summary>
        [Header("Sprites")]
        public Sprite onSpriteSfx;
        
        /// <summary>
        /// Sprite to show when sound effects are disabled
        /// </summary>
        public Sprite offSpriteSfx;
        
        /// <summary>
        /// Sprite to show when music is enabled
        /// </summary>
        public Sprite onSpriteMusic;
        
        /// <summary>
        /// Sprite to show when music is disabled
        /// </summary>
        public Sprite offSpriteMusic;

        /// <summary>
        /// Initializes the component and binds button click events to UI events
        /// </summary>
        void Awake()
        {
            if (startButton) 
                startButton.onClick.AddListener(() => UIEvents.StartFromHome());
            if (resetProgressButton) 
                resetProgressButton.onClick.AddListener(() => UIEvents.ResetProgress());
            if (levelSelectButton) 
                levelSelectButton.onClick.AddListener(() => UIEvents.ShowLevelSelect());
            if (sfxButton) 
                sfxButton.onClick.AddListener(() => UIEvents.ToggleSfx());
            if (musicButton) 
                musicButton.onClick.AddListener(() => UIEvents.ToggleMusic());
            if (exitButton) 
                exitButton.onClick.AddListener(() => UIEvents.Quit());
        }
        
        /// <summary>
        /// Registers audio event handlers when the component is enabled
        /// </summary>
        void OnEnable()
        {
            AudioEvents.OnSfxEnabledChanged += OnSfxChanged;
            AudioEvents.OnMusicEnabledChanged += OnMusicChanged;
        }
        
        /// <summary>
        /// Unregisters audio event handlers when the component is disabled
        /// </summary>
        void OnDisable()
        {
            AudioEvents.OnSfxEnabledChanged -= OnSfxChanged;
            AudioEvents.OnMusicEnabledChanged -= OnMusicChanged;
        }
        
        /// <summary>
        /// Cleans up button click listeners when the component is destroyed
        /// </summary>
        void OnDestroy()
        {
            if (startButton) 
                startButton.onClick.RemoveAllListeners();
            if (resetProgressButton) 
                resetProgressButton.onClick.RemoveAllListeners();
            if (levelSelectButton) 
                levelSelectButton.onClick.RemoveAllListeners();
            if (sfxButton) 
                sfxButton.onClick.RemoveAllListeners();
            if (musicButton) 
                musicButton.onClick.RemoveAllListeners();
            if (exitButton) 
                exitButton.onClick.RemoveAllListeners();
        }
        
        /// <summary>
        /// Updates the sound effects icon when the SFX enabled state changes
        /// </summary>
        /// <param name="enabled">True if SFX are enabled, false if disabled</param>
        void OnSfxChanged(bool enabled)
        {
            if (sfxIcon) 
                sfxIcon.sprite = enabled ? onSpriteSfx : offSpriteSfx;
        }

        /// <summary>
        /// Updates the music icon when the music enabled state changes
        /// </summary>
        /// <param name="enabled">True if music is enabled, false if disabled</param>
        void OnMusicChanged(bool enabled)
        {
            if (musicIcon) 
                musicIcon.sprite = enabled ? onSpriteMusic : offSpriteMusic;
        }
    }
}